version: '3.9'

services:
  airflow:
    image: apache/airflow:2.6.0
    depends_on:
      - mongodb
    entrypoint: /opt/airflow/script/entrypoint.sh
    environment:
      - EXECUTOR=Sequential
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW_WEBSERVER_SECRET_KEY=this_is_a_very_secured_key
    volumes:
      - ./airflow_etl/dags:/opt/airflow/dags
      - ./airflow_etl/script/entrypoint.sh:/opt/airflow/script/entrypoint.sh
      - ./airflow_etl/logs:/opt/airflow/logs
      - ./airflow_etl/data.json:/opt/airflow/data.json
    ports:
      - "8080:8080"
    healthcheck:
      test: ['CMD-SHELL', "[ -f /opt/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - airflow_network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - airflow_network

  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      SUPERSET_SECRET_KEY: "this_is_a_very_secured_key"
      SUPERSET_SQLALCHEMY_DATABASE_URI: "sqlite:////var/lib/superset/superset.db"
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset.db:/var/lib/superset/superset.db
      - ./superset/app:/app
    command: >  
      /bin/bash -c "
      mongosqld --mongo-uri 'mongodb://mongodb:27017' &
      pip install sqlalchemy-drill &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
      superset init &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - airflow_network

  drill:
    image: apache/drill:latest
    container_name: drill
    ports:
      - "8047:8047"
    volumes:
      - ./drill/tmp:/tmp/drill
    command: /opt/drill/bin/drill-embedded
    stdin_open: true
    tty: true
    networks:
      - airflow_network      

networks:
  airflow_network:
    name: airflow_network
