version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: ["python", "main.py"]

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  airflow:
    image: apache/airflow:2.6.0
    container_name: airflow
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////tmp/airflow.db
    ports:
      - "8080:8080"
    volumes:
      - ./airflow_etl/dags:/opt/airflow/dags
      - ./airflow_etl/logs:/opt/airflow/logs
      - ./airflow_etl/utils:/opt/airflow/utils
      - ./airflow_etl/requirements.txt:/opt/airflow/requirements.txt
    command: ["webserver"]
